language: ruby
rvm:
  - 2.2.2
  
branches:
  only:
  - master
  
install:
  - bundle install
before_script:
  - rake build
script: 
  - rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false