language: ruby
rvm:
- 2.1
branches:
  only:
  - master
  
before_script:
- chmod +x ./script/cibuild
- chmod +x ./script/deploy
install:
  - gem install jekyll image_optim image_optim_pack
  - gem install html-proofer -v 3.0.0
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false