# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Sockdrawer: Node.JS apps for forums"
email: yamikuronue@sockdrawer.io
description: > # this means to ignore newlines until "baseurl:"
  SockDrawer is a small open-source organization building Node.JS webapps
  that help make forums more fun
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sockdrawer.io" # the base hostname & protocol for your site
github_username:  SockDrawer

# Build settings
markdown: kramdown
