name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
    - name: deploy to server
      uses: up9cloud/action-rsync@v1.3
      env:
        HOST: ${{ secrets.SERVER_IP }}
        KEY: ${{ secrets.SERVER_SSH_KEY }}
        TARGET: ${{ secrets.SERVER_DESTINATION }}
        USER: ${{ secrets.USERNAME }}
